jobs:
  include:
    - stage: test
      script: echo $VER
      env: VER=FOO
    - stage: test
      script: echo $VER
      env: VER=BAR
    - stage: deploy
      name: Deploy stage
      script: echo "TAG = $TRAVIS_TAG"
